/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AFloatButtonGroup: typeof import('ant-design-vue/es')['FloatButtonGroup']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AudioPlay: typeof import('./src/components/atoms/AudioPlay.vue')['default']
    AuthorInfo: typeof import('./src/components/sidebar/AuthorInfo.vue')['default']
    BannerNav: typeof import('./src/components/banner/BannerNav.vue')['default']
    BannerPC: typeof import('./src/components/banner/BannerPC.vue')['default']
    BannerSP: typeof import('./src/components/banner/BannerSP.vue')['default']
    BaseDialog: typeof import('./src/components/BaseDialog.vue')['default']
    BaseLayout: typeof import('./src/components/layout/BaseLayout.vue')['default']
    BaseLoading: typeof import('./src/components/atoms/BaseLoading.vue')['default']
    BaseSearch: typeof import('./src/components/atoms/BaseSearch.vue')['default']
    BlankContent: typeof import('./src/components/atoms/BlankContent.vue')['default']
    CataLogue: typeof import('./src/components/sidebar/CataLogue.vue')['default']
    ClickVolume: typeof import('./src/components/atoms/clickVolume.vue')['default']
    DownloadDialog: typeof import('./src/components/atoms/DownloadDialog.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    OverLay: typeof import('./src/components/atoms/OverLay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
    TurnLangButton: typeof import('./src/components/atoms/TurnLangButton.vue')['default']
    UserInfo: typeof import('./src/components/atoms/UserInfo.vue')['default']
    UserTag: typeof import('./src/components/atoms/UserTag.vue')['default']
  }
}
