/* tslint:disable */
/* eslint-disable */
/**
 * gin-api
 * gin-api
 *
 * The version of the OpenAPI document: openapi.v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 创建真实的用户所需的参数
 * @export
 * @interface CreateUserParam
 */
export interface CreateUserParam {
    /**
     * 账号
     * @type {string}
     * @memberof CreateUserParam
     */
    'userName': string;
    /**
     * 昵称
     * @type {string}
     * @memberof CreateUserParam
     */
    'name': string;
    /**
     * 密码
     * @type {string}
     * @memberof CreateUserParam
     */
    'password': string;
    /**
     * 身份：1,游客;2,用户;
     * @type {number}
     * @memberof CreateUserParam
     */
    'auth': number;
    /**
     * 邮箱
     * @type {string}
     * @memberof CreateUserParam
     */
    'email'?: string;
    /**
     * 年龄
     * @type {number}
     * @memberof CreateUserParam
     */
    'age'?: number;
}

