/* tslint:disable */
/* eslint-disable */
/**
 * gin-api
 * gin-api
 *
 * The version of the OpenAPI document: openapi.v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import {type GetUserInfoData } from './get-user-info-data';
// May contain unused imports in some cases
// @ts-ignore
import { ResponseStatus } from './response-status';

/**
 * 
 * @export
 * @interface GetUserInfoResponse
 */
export interface GetUserInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof GetUserInfoResponse
     */
    'message': string;
    /**
     * 
     * @type {ResponseStatus}
     * @memberof GetUserInfoResponse
     */
    'status': ResponseStatus;
    /**
     * 
     * @type {GetUserInfoData}
     * @memberof GetUserInfoResponse
     */
    'data': GetUserInfoData;
}



