/* tslint:disable */
/* eslint-disable */
/**
 * gin-api
 * gin-api
 *
 * The version of the OpenAPI document: openapi.v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUserInfoData
 */
export interface GetUserInfoData {
    /**
     * 
     * @type {number}
     * @memberof GetUserInfoData
     */
    'userId': number;
    /**
     * 
     * @type {string}
     * @memberof GetUserInfoData
     */
    'user_name': string;
    /**
     * 
     * @type {string}
     * @memberof GetUserInfoData
     */
    'email'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetUserInfoData
     */
    'auth': number;
    /**
     * 
     * @type {number}
     * @memberof GetUserInfoData
     */
    'age'?: number;
    /**
     * 昵称
     * @type {string}
     * @memberof GetUserInfoData
     */
    'name': string;
}

