/* tslint:disable */
/* eslint-disable */
/**
 * gin-api
 * gin-api
 *
 * The version of the OpenAPI document: openapi.v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetClickVolumeData
 */
export interface GetClickVolumeData {
    /**
     * 网站总点击量
     * @type {number}
     * @memberof GetClickVolumeData
     */
    'web': number;
    /**
     * 笔记点击量
     * @type {number}
     * @memberof GetClickVolumeData
     */
    'note': number;
}

