/* tslint:disable */
/* eslint-disable */
/**
 * gin-api
 * gin-api
 *
 * The version of the OpenAPI document: openapi.v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginParam
 */
export interface LoginParam {
    /**
     * 
     * @type {string}
     * @memberof LoginParam
     */
    'user_name': string;
    /**
     * 
     * @type {string}
     * @memberof LoginParam
     */
    'password': string;
}

