/* tslint:disable */
/* eslint-disable */
/**
 * gin-api
 * gin-api
 *
 * The version of the OpenAPI document: openapi.v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ResponseStatus = {
    Success: 'success',
    Fail: 'fail',
    Error: 'error'
} as const;

export type ResponseStatus = typeof ResponseStatus[keyof typeof ResponseStatus];



