/* tslint:disable */
/* eslint-disable */
/**
 * gin-api
 * gin-api
 *
 * The version of the OpenAPI document: openapi.v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS,type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import {type CommonResponse } from '../model';
// @ts-ignore
import {type GetClickVolumeResponse } from '../model';
// @ts-ignore
import {type SetClickVolumeByTagParam } from '../model';
/**
 * InfoApi - axios parameter creator
 * @export
 */
export const InfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 获取网站点击量
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClickVolume: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 增加点击量
         * @param {SetClickVolumeByTagParam} setClickVolumeByTagParam 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setClickVolumeByTag: async (setClickVolumeByTagParam: SetClickVolumeByTagParam, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'setClickVolumeByTagParam' is not null or undefined
            assertParamExists('setClickVolumeByTag', 'setClickVolumeByTagParam', setClickVolumeByTagParam)
            const localVarPath = `/info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setClickVolumeByTagParam, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InfoApi - functional programming interface
 * @export
 */
export const InfoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InfoApiAxiosParamCreator(configuration)
    return {
        /**
         * 获取网站点击量
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClickVolume(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetClickVolumeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getClickVolume(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['InfoApi.getClickVolume']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 增加点击量
         * @param {SetClickVolumeByTagParam} setClickVolumeByTagParam 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setClickVolumeByTag(setClickVolumeByTagParam: SetClickVolumeByTagParam, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setClickVolumeByTag(setClickVolumeByTagParam, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['InfoApi.setClickVolumeByTag']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * InfoApi - factory interface
 * @export
 */
export const InfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InfoApiFp(configuration)
    return {
        /**
         * 获取网站点击量
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClickVolume(options?: any): AxiosPromise<GetClickVolumeResponse> {
            return localVarFp.getClickVolume(options).then((request) => request(axios, basePath));
        },
        /**
         * 增加点击量
         * @param {SetClickVolumeByTagParam} setClickVolumeByTagParam 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setClickVolumeByTag(setClickVolumeByTagParam: SetClickVolumeByTagParam, options?: any): AxiosPromise<CommonResponse> {
            return localVarFp.setClickVolumeByTag(setClickVolumeByTagParam, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InfoApi - object-oriented interface
 * @export
 * @class InfoApi
 * @extends {BaseAPI}
 */
export class InfoApi extends BaseAPI {
    /**
     * 获取网站点击量
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfoApi
     */
    public getClickVolume(options?: AxiosRequestConfig) {
        return InfoApiFp(this.configuration).getClickVolume(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 增加点击量
     * @param {SetClickVolumeByTagParam} setClickVolumeByTagParam 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfoApi
     */
    public setClickVolumeByTag(setClickVolumeByTagParam: SetClickVolumeByTagParam, options?: AxiosRequestConfig) {
        return InfoApiFp(this.configuration).setClickVolumeByTag(setClickVolumeByTagParam, options).then((request) => request(this.axios, this.basePath));
    }
}

