/* tslint:disable */
/* eslint-disable */
/**
 * gin-api
 * gin-api
 *
 * The version of the OpenAPI document: openapi.v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS,type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import {type GetMDByPathResponse } from '../model';
/**
 * MdApi - axios parameter creator
 * @export
 */
export const MdApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} mdPath 文件路径
         * @param {number} downloadCode 下载码
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadMDByCode: async (mdPath: string, downloadCode: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mdPath' is not null or undefined
            assertParamExists('downloadMDByCode', 'mdPath', mdPath)
            // verify required parameter 'downloadCode' is not null or undefined
            assertParamExists('downloadMDByCode', 'downloadCode', downloadCode)
            const localVarPath = `/md/download`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (mdPath !== undefined) {
                localVarQueryParameter['md_path'] = mdPath;
            }

            if (downloadCode !== undefined) {
                localVarQueryParameter['download_code'] = downloadCode;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} mdPath markdown文件路径
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMarkDownByPath: async (mdPath: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mdPath' is not null or undefined
            assertParamExists('getMarkDownByPath', 'mdPath', mdPath)
            const localVarPath = `/md`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (mdPath !== undefined) {
                localVarQueryParameter['md_path'] = mdPath;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MdApi - functional programming interface
 * @export
 */
export const MdApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MdApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} mdPath 文件路径
         * @param {number} downloadCode 下载码
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadMDByCode(mdPath: string, downloadCode: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadMDByCode(mdPath, downloadCode, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MdApi.downloadMDByCode']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {string} mdPath markdown文件路径
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMarkDownByPath(mdPath: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMDByPathResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMarkDownByPath(mdPath, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MdApi.getMarkDownByPath']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * MdApi - factory interface
 * @export
 */
export const MdApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MdApiFp(configuration)
    return {
        /**
         * 
         * @param {string} mdPath 文件路径
         * @param {number} downloadCode 下载码
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadMDByCode(mdPath: string, downloadCode: number, options?: any): AxiosPromise<File> {
            return localVarFp.downloadMDByCode(mdPath, downloadCode, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} mdPath markdown文件路径
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMarkDownByPath(mdPath: string, options?: any): AxiosPromise<GetMDByPathResponse> {
            return localVarFp.getMarkDownByPath(mdPath, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MdApi - object-oriented interface
 * @export
 * @class MdApi
 * @extends {BaseAPI}
 */
export class MdApi extends BaseAPI {
    /**
     * 
     * @param {string} mdPath 文件路径
     * @param {number} downloadCode 下载码
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MdApi
     */
    public downloadMDByCode(mdPath: string, downloadCode: number, options?: AxiosRequestConfig) {
        return MdApiFp(this.configuration).downloadMDByCode(mdPath, downloadCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} mdPath markdown文件路径
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MdApi
     */
    public getMarkDownByPath(mdPath: string, options?: AxiosRequestConfig) {
        return MdApiFp(this.configuration).getMarkDownByPath(mdPath, options).then((request) => request(this.axios, this.basePath));
    }
}

