openapi: 3.0.2
info:
    title: gin-api
    version: openapi.v3
    description: gin-api
    contact:
        name: yinsiyu
servers:
    -
        url: 'http://0.0.0.0:8849/api'
        description: ''
paths:
    /md:
        get:
            tags:
                - md
            parameters:
                -
                    name: md_path
                    description: markdown文件路径
                    schema:
                        type: string
                    in: query
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetMDByPathResponse'
                    description: 获取成功！
            operationId: GetMarkDownByPath
    /md/download:
        get:
            tags:
                - md
            parameters:
                -
                    name: md_path
                    description: 文件路径
                    schema:
                        type: string
                    in: query
                    required: true
                -
                    name: download_code
                    description: 下载码
                    schema:
                        type: integer
                    in: query
                    required: true
            responses:
                '200':
                    content:
                        text/markdown:
                            schema:
                                format: binary
                                type: string
                    description: 下载成功！
            operationId: DownloadMDByCode
    /info:
        get:
            tags:
                - info
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetClickVolumeResponse'
                    description: 获取网站点击量
            operationId: GetClickVolume
            description: 获取网站点击量
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SetClickVolumeByTagParam'
                required: true
            tags:
                - info
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CommonResponse'
                    description: 浏览量+1！
            operationId: SetClickVolumeByTag
            description: 增加点击量
    /user/create:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateUserParam'
                required: true
            tags:
                - User
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CommonResponse'
                    description: 创建成功！
            operationId: CreateUser
            description: 创建真实用户
    /user/info:
        get:
            tags:
                - User
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetUserInfoResponse'
                    description: 获取当前user信息
            security:
                -
                    token: []
            operationId: GetUserInfo
            description: 获取用户信息成功！
    /login:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginParam'
                required: true
            tags:
                - login
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CommonResponse'
                    description: 登录成功！
            operationId: LoginByUserName
components:
    schemas:
        CommonResponse:
            description: ''
            required:
                - message
                - status
            type: object
            properties:
                message:
                    description: ''
                    type: string
                status:
                    $ref: '#/components/schemas/ResponseStatus'
                    description: ''
        ResponseStatus:
            description: ''
            enum:
                - success
                - fail
                - error
            type: string
        GetMDByPathResponse:
            description: ''
            required:
                - message
                - status
                - data
            type: object
            properties:
                message:
                    description: ''
                    type: string
                status:
                    $ref: '#/components/schemas/ResponseStatus'
                    description: ''
                data:
                    description: ''
                    type: string
        GetClickVolumeData:
            description: ''
            required:
                - web
                - note
            type: object
            properties:
                web:
                    description: 网站总点击量
                    type: integer
                note:
                    description: 笔记点击量
                    type: integer
        GetClickVolumeResponse:
            description: ''
            required:
                - message
                - status
                - data
            type: object
            properties:
                message:
                    description: ''
                    type: string
                status:
                    $ref: '#/components/schemas/ResponseStatus'
                    description: ''
                data:
                    $ref: '#/components/schemas/GetClickVolumeData'
                    description: ''
        SetClickVolumeByTagParam:
            description: ''
            required:
                - tag
            type: object
            properties:
                tag:
                    description: ''
                    type: string
        CreateUserParam:
            description: 创建真实的用户所需的参数
            required:
                - userName
                - name
                - password
                - auth
            type: object
            properties:
                userName:
                    description: 账号
                    type: string
                name:
                    description: 昵称
                    type: string
                password:
                    description: 密码
                    type: string
                auth:
                    description: '身份：1,游客;2,用户;'
                    type: integer
                email:
                    description: 邮箱
                    type: string
                age:
                    description: 年龄
                    type: integer
        GetUserInfoResponse:
            description: ''
            required:
                - message
                - status
                - data
            type: object
            properties:
                message:
                    description: ''
                    type: string
                status:
                    $ref: '#/components/schemas/ResponseStatus'
                    description: ''
                data:
                    $ref: '#/components/schemas/GetUserInfoData'
                    description: ''
        GetUserInfoData:
            description: ''
            required:
                - userId
                - user_name
                - auth
                - name
            type: object
            properties:
                userId:
                    description: ''
                    type: integer
                user_name:
                    description: ''
                    type: string
                email:
                    description: ''
                    type: string
                auth:
                    description: ''
                    type: integer
                age:
                    description: ''
                    type: integer
                name:
                    description: 昵称
                    type: string
        LoginParam:
            description: ''
            required:
                - user_name
                - password
            type: object
            properties:
                user_name:
                    description: ''
                    type: string
                password:
                    description: ''
                    type: string
    securitySchemes:
        token:
            scheme: bearer
            type: http
tags:
    -
        name: md
        description: markdown文件相关
    -
        name: info
        description: 获取网站基本信息
    -
        name: User
        description: 用户
    -
        name: login
        description: 登录
